services:
  - type: web
    name: todo-backend
    runtime: docker             # vì bạn dùng Dockerfile
    plan: free
    rootDir: todo-app-backend   # thư mục chứa Dockerfile

    autoDeploy: true

    envVars:
      # 👉 PostgreSQL (internal database)
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d1uhf1adbo4c73ejtf80-a.internal:5432/todo_db_ml5v
      - key: SPRING_DATASOURCE_USERNAME
        value: todo_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: nY9J0wJDNz0ZFdmiO1T89SPMGVkjTdea

      # 👉 Hibernate
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "true"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
        value: "true"

      # 👉 SQL Logs (debug)
      - key: LOGGING_LEVEL_ORG_HIBERNATE_SQL
        value: DEBUG
      - key: LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER
        value: TRACE

      # 👉 CORS cho GitHub Pages (React Vite)
      - key: SPRING_WEB_CORS_ALLOWED_ORIGINS
        value: https://tranvanmanh9325.github.io

      # 👉 Server port
      - key: PORT
        value: "8080"