services:
  - type: web
    name: todo-backend
    runtime: docker
    plan: free
    rootDir: todo-app-backend  # Thư mục chứa Dockerfile và mã nguồn backend
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d1uhf1adbo4c73ejtf80-a:5432/todo_db_ml5v
      - key: SPRING_DATASOURCE_USERNAME
        value: todo_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: nY9J0wJDNz0ZFdmiO1T89SPMGVkjTdea
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_WEB_CORS_ALLOWED_ORIGINS
        value: http://localhost:5173,https://tranvanmanh9325.github.io