services:
  - type: web
    name: todo-backend
    env: java
    plan: free
    rootDir: todo-app-backend
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    autoDeploy: true

    envVars:
      # 👉 PostgreSQL config
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d1uhf1adbo4c73ejtf80-a:5432/todo_db_ml5v
      - key: SPRING_DATASOURCE_USERNAME
        value: todo_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: nY9J0wJDNz0ZFdmiO1T89SPMGVkjTdea

      # 👉 Hibernate config
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "true"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
        value: "true"

      # 👉 SQL logs
      - key: LOGGING_LEVEL_ORG_HIBERNATE_SQL
        value: DEBUG
      - key: LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER
        value: TRACE

      # 👉 CORS
      - key: SPRING_WEB_CORS_ALLOWED_ORIGINS
        value: http://localhost:5173,https://tranvanmanh9325.github.io

      # 👉 Other
      - key: PORT
        value: "8080"