services:
  - type: web
    name: todo-backend
    runtime: docker                       # ✅ Bạn đang dùng Dockerfile
    plan: free
    rootDir: todo-app-backend
    autoDeploy: true

    envVars:
      # 👉 PostgreSQL connection
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d1uhf1adbo4c73ejtf80-a:5432/todo_db_ml5v
      - key: SPRING_DATASOURCE_USERNAME
        value: todo_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: nY9J0wJDNz0ZFdmiO1T89SPMGVkjTdea

      # 👉 Hibernate
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "true"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
        value: "true"

      # 👉 SQL logs
      - key: LOGGING_LEVEL_ORG_HIBERNATE_SQL
        value: DEBUG
      - key: LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER
        value: TRACE

      # 👉 CORS — chỉ cho phép GitHub Pages frontend
      - key: SPRING_WEB_CORS_ALLOWED_ORIGINS
        value: https://tranvanmanh9325.github.io

      # 👉 Port (Render sẽ inject, nhưng tốt nhất đặt default)
      - key: PORT
        value: "8080"